
services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: fleetlink-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fleetlink
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - fleetlink-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fleetlink-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/fleetlink?authSource=admin
    depends_on:
      - mongodb
    networks:
      - fleetlink-network
    volumes:
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fleetlink-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:5000
    depends_on:
      - backend
    networks:
      - fleetlink-network
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/.env.local:/app/.env.local

volumes:
  mongodb_data:

networks:
  fleetlink-network:
    driver: bridge
